name: E2E Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fs: ['overlayfs']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        run: |
          docker buildx build . -t docker-e2e

      - name: Run
        run: |
          docker run --rm -it --privileged --name docker-e2e
        
