name: E2E MacOS (GitHub Actions)

on:
  workflow_call:
    
jobs:
    macos-e2e:
        runs-on: macos-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup Rust
          uses: actions-rs/toolchain@v1
          with:
                profile: minimal
                toolchain: stable
                override: true

        - name: Run Tests
          run: cargo test
      